### ISSUE TITLE
Doesn't work after update 2.1.0 on Opera

### ISSUE THREAD

**Issue by aaashleyyyy** [OvalQuilter/lyrics-status#2] opened 2022-10-10 23:53 UTC
https://user-images.githubusercontent.com/83358470/194969161-4f93493b-af2f-480d-a912-ebe6e4d6eb3e.mp4

**Comment by aaashleyyyy** [comment] 2022-10-10 23:56
^^ the buttons dont do anything anymore

**Comment by aaashleyyyy** [comment] 2022-10-11 00:11
Nevermind, it just seems to only work on Google Chrome.

**Comment by OvalQuilter** [comment] 2022-10-11 13:59
👋Hello. Thanks for reporting the bug!
Can you please open devtools (**Ctrl + Shift + I** or **F12**) and send me screenshot from console?
I need more information because I can't reproduce the bug though I also use Opera.
By the way, what version of Opera you use? You can check it by going to _opera://update/_

**Comment by aaashleyyyy** [comment] 2022-10-11 14:32
> 👋Hello. Thanks for reporting the bug! Can you please open devtools (**Ctrl + Shift + I** or **F12**) and send me screenshot from console? I need more information because I can't reproduce the bug though I also use Opera. By the way, what version of Opera you use? You can check it by going to _opera://update/_

It's Opera GX specifically, I should add. Lemme get all that information real quick.

**Comment by aaashleyyyy** [comment] 2022-10-11 14:41
This must be an issue my end, because on my laptop the script works fine on Opera GX. I'll try uninstalling Opera GX then reinstalling when I'm home.

**Comment by aaashleyyyy** [comment] 2022-10-11 16:58
This has started to happen on chrome as well

`Uncaught TypeError: Cannot read properties of undefined (reading 'enabled')
    at loadSettings (eval at <anonymous> (sensitivedatathing:16:98), <anonymous>:675:28)
    at eval (eval at <anonymous> (sensitivedatathing:16:98), <anonymous>:819:1)
    at Object.success (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:16:98)
    at c (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:28327)
    at Object.fireWith [as resolveWith] (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:29072)
    at l (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:79901)
    at XMLHttpRequest.<anonymous> (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:82355)
    at XMLHttpRequest.r (vendor~web-player.6be52b13.js:1:77288)`

**Comment by OvalQuilter** [comment] 2022-10-11 18:04
> This has started to happen on chrome as well
> 
> `Uncaught TypeError: Cannot read properties of undefined (reading 'enabled') at loadSettings (eval at <anonymous> (sensitivedatathing:16:98), <anonymous>:675:28) at eval (eval at <anonymous> (sensitivedatathing:16:98), <anonymous>:819:1) at Object.success (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:16:98) at c (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:28327) at Object.fireWith [as resolveWith] (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:29072) at l (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:79901) at XMLHttpRequest.<anonymous> (userscript.html?name=Lyrics'%2520sender%2520V2.user.js&id=9d64b446-73ac-4954-9245-5bfc4ddc54f1:3:82355) at XMLHttpRequest.r (vendor~web-player.6be52b13.js:1:77288)`


This is known issue and will be fixed in next update. You can temporarily fix it by yourself, just open devtools and delete settings property (Application tab):
![screenshot](https://user-images.githubusercontent.com/69106951/195165539-a2442955-ce28-451b-bb4f-b5d36d615eff.png)
You'll need to configure script again.
If this won't help please tell me, thanks.

**Closed** 2022-10-16 13:17 UTC
